### ISSUE TITLE
There is a styling issue after closing the viewer with red rectangle on the top right

### ISSUE THREAD

**Issue by Plexprofile** [duydl/logseq-calibre-plugin#3]
When the viewer is closed, the active editing pane slides automatically toward the right without getting back to the initial position, causing it to overlap with the right sidebar and leaving an area of blank space on the left
![bug](https://github.com/duydl/logseq-calibre-annotation/assets/139643082/9ece1ce9-ef33-400d-8bbd-99b2af803546)

**Comment by duydl** [comment]
I am aware of the overlapping with the right sidebar bug but the empty area is probably due to its reaction with other plugins as I cannot reproduce it. 
As Logseq API provides limited ability to control or even inspect UI of the main interface, I am still working on a way to fix that fully. There would be a semi-workaround in the next update.

**Comment by duydl** [comment]
Tell me if you still have this issue with v1.1.1.

**Comment by Plexprofile** [comment]
In v1.1.1 the UI is back to normal after viewer is closed, but when the viewer is turn on it is shown on the right of the sidebar instead of taking the place of it, causing the ui to look crowed (even after the right sidebar is closed)
![bug](https://github.com/duydl/logseq-calibre-annotation/assets/139643082/cc95f5ab-f699-4a92-ad14-34a44a82686a)

**Comment by duydl** [comment]
There is a setting in the calibre-annotation to adjust the width. The default is 50%. 
 In the future I will ask a draggable cursor, to adjust the viewer width while reading.
