### ISSUE TITLE
"Close viewer" button is missing

### ISSUE THREAD

**Issue by VictorVow** [duydl/logseq-calibre-plugin#6]
![image](https://github.com/duydl/logseq-calibre-annotation/assets/12621257/709885e4-41f6-4961-a6a6-2dbba772f00b)

I don't see any red rectangle to close viewer, and clicking that area doesn't do anything either.

Linux
calibreAnnotation 1.2.0
Logseq 0.9.19

**Comment by duydl** [comment]
Hi. The red button was already replaced. You could close the viewer with a button on a moveable option bar. I already updated the demo in README to reflect the change. 
You could not see the bar probably because some other UI addons covered the top of the viewer. I have updated the height of the viewer to reduce the chance of conflict and make the bar appear in the center of the viewer.

**Comment by VictorVow** [comment]
Thanks, I'm able to close the viewer now. It might have been Awesome UI plugin that conflicted with it.
